// plugins/docs.js
//
// Swagger spec + Swagger UI at /api-docs. The spec is pre-generated by
// swagger-autogen.js (npm run dev/start regenerate it), so this serves a
// static document rather than introspecting routes at boot.

const fp = require('fastify-plugin');
const fastifySwagger = require('@fastify/swagger');
const fastifySwaggerUi = require('@fastify/swagger-ui');
const { pluginLoaded } = require('../utils/bootBanner');

module.exports = fp(async function docs(fastify) {
  fastify.register(fastifySwagger, {
    mode: 'static',
    specification: {
      document: require('../swagger_output.json'),
    },
  });
  fastify.after(() => pluginLoaded('swagger'));

  fastify.register(fastifySwaggerUi, {
    routePrefix: '/api-docs',
    uiConfig: {
      docExpansion: 'list',
      deepLinking: true,
    },
    staticCSP: true, // Swagger UI sets its own CSP for its bundled assets, independent of the strict global policy
    exposeRoute: true,
  });
  fastify.after(() => pluginLoaded('swagger-ui'));
});
